"""Including property in ReipeIngredients and RecipeTools for pydantic.

Revision ID: 30c4e29e87ce
Revises: 4d524df47fc2
Create Date: 2026-02-24 17:45:37.102734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c4e29e87ce'
down_revision: Union[str, Sequence[str], None] = '4d524df47fc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
