"""Including association_proxy in Recipes.

Revision ID: 4d524df47fc2
Revises: 17dc7cd8a5fa
Create Date: 2026-02-24 17:19:31.831735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d524df47fc2'
down_revision: Union[str, Sequence[str], None] = '17dc7cd8a5fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
