"""Including column image_url in Recipes.

Revision ID: 8b4d40004dab
Revises: 30c4e29e87ce
Create Date: 2026-02-26 15:18:16.280206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4d40004dab'
down_revision: Union[str, Sequence[str], None] = '30c4e29e87ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipes', sa.Column('image_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipes', 'image_url')
    # ### end Alembic commands ###
