"""Extension of RecipeIngredients with the column component

Revision ID: d17107a03d1c
Revises: 93ac4d536e91
Create Date: 2026-02-20 15:14:43.940383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17107a03d1c'
down_revision: Union[str, Sequence[str], None] = '93ac4d536e91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_ingredients', sa.Column('component', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'component')
    # ### end Alembic commands ###
